### ISSUE TITLE
[ADD Server] eggy.cc

### ISSUE THREAD

**Issue by eggy** [Atreatis/matrixservers#10]
**Type:** Hobby 
**Server name:**  Eggy Homeserver
**Domain:**  eggy.cc
**Maintainer:**  @eggy:eggy.cc
**Support Channel:** #eggster:eggy.cc
**Founded:**  2017
**Web client:** http://eggy.im
**Description:** Homeserver server known for providing the irchighway matrix IRC bridge. Registration is open, anybody is welcome to join.

**Comment by Atreatis** [comment]
Added to the API, it should update in a bit 👍
