### ISSUE TITLE
[ADD Server] mental.af

### ISSUE THREAD

**Issue by mathilde-blc** [Atreatis/matrixservers#11]
**Type:** Hobby
**Server name:**  Mental AF
**Domain:**  mental.af
**Maintainer:**  @mathilde:mental.af
**Support Channel:** #home:mental.af
**Founded:**  2018
**Web client:** Riot IM at https://chat.mental.af
**Description:** mental.af is another space on the decentralized web, made by and for the deranged. Very strict moderation rules are enforced here, and beware: freespeech advocates aren't welcomed.

**Comment by Atreatis** [comment]
Added to the API together with #10 it should display in about 5 minutes on the website. Keep in-mind with the leverage browser caching on the website, so a hard refresh may be necessary.
