### ISSUE TITLE
Listing matrix.spider.ink

### ISSUE THREAD

**Issue by serra-allgood** [Atreatis/matrixservers#12]
I'd like to add matrix.spider.ink to the list of servers. I am the maintainer and agree to follow and enforce the CoC. 

The server is general purpose, though attracting people interested in contributing to Matrix and other federated projects would be great. Registration is semi-open, please contact jump_spider@spider.ink if interested.

**Comment by Atreatis** [comment]
Goodmorning,

Could you provide the following information:
Type: Hobby / Organization / Professional
Server name:
Domain:
Maintainer:
Support Channel: Founded:
Web client: Description:

That would make it much easier to add :)

**Comment by serra-allgood** [comment]
Ah, my apologies!

Type: Hobby
Server name: matrix.spider.ink
Domain: matrix.spider.ink
Maintainer @jump_spider:matrix.spider.ink
Support Channel: #support:matrix.spider.ink
Founded: 2019
Web client: None right now, but plans to host Riot
Description: General purpose server with a leaning towards programming and technology. As the user base grows, bots, bridges, custom integration server, workers, and possibly custom identity server are on the roadmap. LGBTQIA+ encouraged to join! Registrations are semi-open, please contact jump_spider AT spider DOT ink if interested.

**Comment by Atreatis** [comment]
No worries mate, unfortunately my GPU popped yesterday which made my PC completely useless due no on-board GPU or APU will be adding your server right away

**Comment by Atreatis** [comment]
Added and published, make sure to hard refresh once the build of the site has been finished (usually takes 5 minutes) 👍
