### ISSUE TITLE
[ADD Server] matrix.gibberfish.org

### ISSUE THREAD

**Issue by gibberfishinc** [Atreatis/matrixservers#13]
**Type:** Organization
**Server name:**  matrix.gibberfish.org
**Domain:**  matrix.gibberfish.org
**Maintainer:**  @blacksam:matrix.gibberfish.org
**Support Channel:** #help:matrix.gibberfish.org
**Founded:**  June 18, 2019
**Web client:** riot-web
**Description:** Gibberfish is a US-based non-profit dedicated to promoting privacy and decentralization. All private data on this server are encrypted in-flight and at-rest, and are backed up daily. We do not log IP addresses.

**Comment by Atreatis** [comment]
Server has been added and published 👍
