### ISSUE TITLE
[Delist] mental.af

### ISSUE THREAD

**Issue by mathilde-blc** [Atreatis/matrixservers#14]
**Server name:**  Mental AF
**Server domain:**  mental.af
**Admin contact:** @mathilde-blc

**Are you the maintainer?** YES

**Comment by Atreatis** [comment]
Will fix it right away

**Comment by mathilde-blc** [comment]
> Will fix it right away

many thanks!

**Comment by mathilde-blc** [comment]
hello,

any news @Atreatis ?

**Comment by Atreatis** [comment]
Forgotten to close this but it's delisted 👍

**Comment by mathilde-blc** [comment]
hi @Atreatis,

thanks for answering, however https://stats.matrixservers.net/service/mental.af is still up and you can still see the instance on the homepage.

<img width="886" alt="Screenshot 2019-07-03 at 18 11 14" src="https://user-images.githubusercontent.com/41020854/60607650-fe292580-9dbd-11e9-82f1-c7e74d5a7c79.png">

**Comment by Atreatis** [comment]
My apologies, should be removed now from stats as well.

**Comment by mathilde-blc** [comment]
> My apologies, should be removed now from stats as well.

thanks for answering but https://stats.matrixservers.net/service/mental.af is still up

**Comment by Atreatis** [comment]
This time I double checked, it's gone now 👍

**Comment by mathilde-blc** [comment]
many thanks!
