### ISSUE TITLE
[ADD]

### ISSUE THREAD

**Issue by mtippmann** [Atreatis/matrixservers#4]
**Server name:**  matrix.bau-ha.us
**Domain:**  bau-ha.us
**Maintainer:**  mt:bau-ha.us 
**Founded:**  2018
**Web client:**  matrix.bau-ha.us (Riot)
**Description:** Synapse with workers, TURN-Server (UDP), Telegram-Bridge, XMPP-Bridge, hostet at Uni-Weimar by student run Hackspace (maschinenraum.tk), dedicated server, 
**Support:** #meta:bau-ha.us

**Comment by Atreatis** [comment]
Server has been listed and added :)
