### ISSUE TITLE
[ADD] grin.hu

### ISSUE THREAD

**Issue by grinapo** [Atreatis/matrixservers#5]
**Server name:**  matrix.grin.hu
**Domain:**  grin.hu
**Maintainer:**  @grin:grin.hu
**Founded:**  2019-01
**Web client:**  https://riot.grin.hu/
**Description:** One of the various services provided by this suspicious individual. Image limit is 2 MB, captcha active, the server is synapse with workers, unless there's a faster one. Registrations otherwise open. Admin reserves the right to be impolite with impolite people to any extent.

**Comment by Atreatis** [comment]
It seems your server is giving a 502 error upon testing for federation, mind checking that out?

The test I am using is:
https://federationtester.matrix.org/

Which currently fails.

**Comment by Atreatis** [comment]
Server has been added 👍
