### ISSUE TITLE
Github link is obscure

### ISSUE THREAD

**Issue by Half-Shot** [Atreatis/matrixservers#7]
I found it eventually at the bottom of the About page, but surely we can have one of those fancy ribbons in the top right corner or at least some button on the front page?

**Comment by Atreatis** [comment]
Sure thing, will add a link to Github with the menu, sorry for the late reply kind of got distracted with Graphsql :)

**Comment by Atreatis** [comment]
Added it discretely to the end of the menu's, hopefully this will satisfy the needs for finding the link to Github. The reason that I added it to the menu's instead is because those banners are quite intrusive in my vision when I looked at the examples :)

**Comment by Half-Shot** [comment]
Works for me :)
