### ISSUE TITLE
[ADD] potatofrom.space

### ISSUE THREAD

**Issue by Pneumaticat** [Atreatis/matrixservers#8]
**Type** Hobby
**Server name:** potatofrom.space
**Domain:** https://potatofrom.space
**Maintainer:**  https://matrix.to/#/@kevin:potatofrom.space
**Support Channel:**  https://matrix.to/#/#home:potatofrom.space
**Founded:** 2019-06-08
**Web client:** https://riot.potatofrom.space
**Description:** A self-hosted Matrix server opened up to the public to encourage greater network adoption and decentralization. Join if you like potatoes, space, or both in combination. One nine of uptime guaranteed, or your money back.

**Comment by Atreatis** [comment]
Server has been added to the API, it should display once Travis-CI has done rebuilding building the website 🚧

**Comment by Atreatis** [comment]
And it's listed, make sure to hard refresh due leverage browser caching ;)
