### ISSUE TITLE
[ADD Server] Nheko.im

### ISSUE THREAD

**Issue by redsky17** [Atreatis/matrixservers#9]
**Type** Hobby / Organization
**Server name:**  Nheko Homeserver
**Domain:**  https://matrix.nheko.im
**Maintainer:**  @red_sky:nheko.im
**Support Channel:** #nhekoim:nheko.im
**Founded:**  2019
**Web client:** neo/iris https://matrix.nheko.im/webchat
**Description:** Homeserver run by one of the maintainers of nheko.  Free for anyone to join!

**Comment by Atreatis** [comment]
Added to the list Travis is rebuilding as of we speak 👍
